In [2]:
import pandas as pd
import os
# warnings 무시
import warnings
warnings.filterwarnings('ignore')

In [3]:
files = os.listdir('/Users/parkseongwoo/Desktop/REITs/REITs/data')
files

['한화리츠.xlsx',
 '케이탑리츠.xlsx',
 '디앤디플랫폼리츠.xlsx',
 '미래에셋글로벌리츠.xlsx',
 '모두투어리츠.xlsx',
 '코람코에너지리츠.xlsx',
 '이지스밸류리츠.xlsx',
 'SK리츠.xlsx',
 '신한알파리츠.xlsx',
 'ESR켄달스퀘어리츠.xlsx',
 '에이리츠.xlsx',
 '삼성FN리츠.xlsx',
 'REITs data.ipynb',
 '이리츠코크렙.xlsx',
 'NH프라임리츠.xlsx',
 '마스턴프리미어리츠.xlsx',
 'NH올원리츠.xlsx',
 '코람코더원리츠.xlsx',
 '롯데리츠.xlsx',
 'KB스타리츠.xlsx',
 '.ipynb_checkpoints',
 '신한서부티엔디리츠.xlsx',
 '미래에셋맵스리츠.xlsx',
 '제이알글로벌리츠.xlsx',
 '이지스레지던스리츠.xlsx']

In [6]:
# 리츠 주가 데이터
path1 = '/Users/parkseongwoo/Desktop/REITs/REITs/data/' 
file_list1 = os.listdir(path1)  
file_list_py1 = [file for file in file_list1 if file.endswith('.xlsx')]

In [16]:
리츠명 = []
for i in range(len(file_list_py1)):
    a = file_list_py1[i].split('.')[0]
    리츠명.append(a)

In [18]:
index = []
for i in range(len(file_list1)):
    index.append(i)

In [ ]:
에이리츠

In [37]:
리츠주가_df = 
for i, j in zip(file_list_py1,index):
    data1 = pd.read_excel(path1 + i)
    data1 = data1[['일자','종가']]
    data1.rename(columns={'종가':리츠명[j]}, inplace=True)
    리츠주가_df = pd.concat([리츠주가_df,data1],axis = 1)

In [40]:
리츠주가_df

,일자,한화리츠,일자,케이탑리츠,일자,디앤디플랫폼리츠,일자,미래에셋글로벌리츠,일자,모두투어리츠,...,일자,KB스타리츠,일자,신한서부티엔디리츠,일자,미래에셋맵스리츠,일자,제이알글로벌리츠,일자,이지스레지던스리츠
0,2023/07/12,5250.0,2023/07/12,1009.0,2023/07/12,3180.0,2023/07/12,3290.0,2023/07/12,3770.0,...,2023/07/12,4290.0,2023/07/12,3210.0,2023/07/12,3170.0,2023/07/12,4160.0,2023/07/12,3765.0
1,2023/07/11,5220.0,2023/07/11,1012.0,2023/07/11,3170.0,2023/07/11,3305.0,2023/07/11,3805.0,...,2023/07/11,4290.0,2023/07/11,3220.0,2023/07/11,3170.0,2023/07/11,4140.0,2023/07/11,3770.0
2,2023/07/10,5330.0,2023/07/10,1007.0,2023/07/10,3170.0,2023/07/10,3300.0,2023/07/10,3755.0,...,2023/07/10,4245.0,2023/07/10,3235.0,2023/07/10,3160.0,2023/07/10,4040.0,2023/07/10,3795.0
3,2023/07/07,5340.0,2023/07/07,1006.0,2023/07/07,3210.0,2023/07/07,3310.0,2023/07/07,3805.0,...,2023/07/07,4245.0,2023/07/07,3280.0,2023/07/07,3150.0,2023/07/07,4080.0,2023/07/07,3805.0
4,2023/07/06,5290.0,2023/07/06,1001.0,2023/07/06,3225.0,2023/07/06,3305.0,2023/07/06,3820.0,...,2023/07/06,4310.0,2023/07/06,3295.0,2023/07/06,3240.0,2023/07/06,4120.0,2023/07/06,3810.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2952,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2953,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2954,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2955,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2956,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN